name: Deploy Explorer - PROD - From Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Simulate deployment from branch
        run: |
          echo "Deploying branch ${{ github.event.inputs.branch }} to PROD..."
          sleep 5
          echo "Branch deployment completed successfully!" 