name: Telegram Notification

on:
  workflow_run:
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          echo "Secret exists check (should be true): ${{ secrets.TG_DEPLOY_CHAT_ID != '' }}"
          echo "Token exists check (should be true): ${{ secrets.TG_DEPLOY_TOKEN != '' }}"
      
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_DEPLOY_CHAT_ID }}
          token: ${{ secrets.TG_DEPLOY_TOKEN }}
          format: markdown
          debug: true
          message: |
            *GitHub Actions Workflow Notification*
            
            *Workflow*: ${{ github.event.workflow_run.name }}
            *Status*: ${{ github.event.workflow_run.conclusion == 'success' && '✅ Success' || github.event.workflow_run.conclusion == 'failure' && '❌ Failed' || github.event.workflow_run.conclusion == 'cancelled' && '⚠️ Cancelled' || github.event.workflow_run.conclusion }}
            *Branch/Tag*: ${{ github.event.workflow_run.head_branch }}
            
            *Triggered by*: ${{ github.event.workflow_run.triggering_actor.login }}
            *Repository*: ${{ github.repository }}
            
            *Workflow run URL*: ${{ github.event.workflow_run.html_url }} 
