name: Telegram Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          echo "Secret exists check (should be true): ${{ secrets.TG_DEPLOY_CHAT_ID != '' }}"
          echo "Token exists check (should be true): ${{ secrets.TG_DEPLOY_TOKEN != '' }}"
      
      - name: Send simple Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_DEPLOY_CHAT_ID }}
          token: ${{ secrets.TG_DEPLOY_TOKEN }}
          message: "Test message from GitHub Actions"
          debug: true 